// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Data;

#nullable disable

namespace NotificationService.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230826161642_InitDBNotification")]
    partial class InitDBNotification
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NotificationService.Model.Notifications", b =>
                {
                    b.Property<string>("IdNotification")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContentNotification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdSender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdNotification");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("NotificationService.Model.Receiver", b =>
                {
                    b.Property<string>("Idreceiver")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdNotification")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Idreceiver");

                    b.HasIndex("IdNotification");

                    b.ToTable("receivers");
                });

            modelBuilder.Entity("NotificationService.Model.Receiver", b =>
                {
                    b.HasOne("NotificationService.Model.Notifications", "notifications")
                        .WithMany("receivers")
                        .HasForeignKey("IdNotification")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_nguoinhan_thongbao");

                    b.Navigation("notifications");
                });

            modelBuilder.Entity("NotificationService.Model.Notifications", b =>
                {
                    b.Navigation("receivers");
                });
#pragma warning restore 612, 618
        }
    }
}
